Add check for 'nvim' environment variable in 'esc' script
The commit adds a check for the presence of the 'nvim' environment variable in the 'esc' script. If 'nvim' is not set, the script now displays an error message and exits with a non-zero status code. This helps to ensure that the script will work correctly even if 'nvim' is not set or set to an invalid value.

diff --git a/src/.local/bin/esc b/src/.local/bin/esc
--- a/src/.local/bin/esc
+++ b/src/.local/bin/esc
@@ -13,4 +13,9 @@ if [[ -z "${filePath}" ]]; then
     exit 1
 fi
 
+if [[ -z "${EDITOR}" ]]; then
+    printf "Error: \${EDITOR} not set." >&2
+    printf "\n"
+    exit 1
+fi
 ${EDITOR} "${filePath}"
